version: "3"
services:
  api:
    image: node:16
    working_dir: /usr/src/app/
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=r3d1sc4ch3
      # - PUBLIC_URL=/trial-monitor
    volumes:
      - ./packages/server:/usr/src/app/
      - ./config:/usr/config
      - ./data/logs/api/:/usr/src/app/logs/
    command: /bin/sh -c 'chmod +x /usr/src/app/dev-start.sh && /usr/src/app/dev-start.sh'
    ports:
      - '3001:3001'
    depends_on:
      - redis_cache
  frontend:
    image: node:16
    working_dir: /usr/src/app/
    # environment:
    #   - PUBLIC_URL=/trial-monitor
    #   - API_URL=
    volumes:
      - ./packages/client:/usr/src/app/
      - ./packages/client-common:/usr/src/client-common/
    command: /bin/sh -c 'chmod +x /usr/src/app/dev-start.sh && /usr/src/app/dev-start.sh'
    ports:
      - '8080:8080'
  editor:
    image: node:16
    working_dir: /usr/src/app/
    # environment:
    #   - PUBLIC_URL=/trial-monitor
    #   - API_URL=
    volumes:
      - ./packages/editor:/usr/src/app/
      - ./packages/client-common:/usr/src/client-common/
    command: /bin/sh -c 'chmod +x /usr/src/app/dev-start.sh && /usr/src/app/dev-start.sh'
    expose:
      - 8080
    ports:
      - '8181:8080'
  nginx_proxy:
    image: nginx:1.21-alpine
    environment:
      - API_PORT=3001
      - FRONTEND_PORT=8080
      - EDITOR_PORT=8080
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./data/logs/nginx/:/var/log/nginx/
    links:
      - api:api
      - frontend:frontend
      - editor:editor
    depends_on:
      - api
      - frontend
      - editor
    ports:
      - "80:80"
  redis_cache:
    image: redis:alpine3.15
    command: redis-server --requirepass r3d1sc4ch3
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./data/redis:/var/lib/redis
    ports:
      - "6379:6379"
